language: node_js
node_js:
  - "node"
notifications:
  email: false
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
install:
  - npm ci
script:
  - npm start
  - npm run start:ci &
  - npm run cy:run -- --record --key a6f754d5-999f-4710-ba66-17f075071e70
  - kill $(jobs -p) || true